vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        bungalow_image: # Changer le nom du mapping ici
           uri_prefix: /images/bungalows
           upload_destination: '%kernel.project_dir%/public/images/bungalow'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


